import React from "react"
import screenshot from '../images/subway.png'
import Layout from "../components/layout"
import Image from "../components/image"
import SEO from "../components/seo"
import Project from "../components/layout-project"

const AiArtPage = () => (
  <Layout>
    <SEO title="ai+art" />
    <Project
      title="ai+art"
      keywords="Data Visualization, Deep Learning"
      skills="RunwayML, HTML, CSS"
      >
        <div className='Project-body'>
        ai+art is a project that developed out of my interest in understanding deep learning techniques and generative adversial networks. It consists of 2 experiments, sydpix+flowers and selfie+nebula. I used RunwayML, a machine learning tool for creatives, and StyleGAN as the deep learning algorithm responsible for image generation.
        </div>
        <div className='Project-body'>
        The first experiment, sydpix+flowers, was trained with a random selection of 500 of my photos from this past year and used a model that had been pre-trained on 620 flower photos. The second experiment, selfie+nebula, was trained with 250 selfies and a model that had been pre-trained on photos of nebula. Once trained, the model generated its own images that resembled morphed versions of the flowers or nebula and iPhone photos. More details about experiment results can be found on this webpage.
        </div>
        <img src={screenshot} />

        <div className='Project-body'>
          <h4>Related Work: "Millefolium"</h4>
          <p>Additional exploration of these experiments is being done in collaboration with artist Haley Pisciotta. Our first study, "Millefolium" is a painting based on one output of sydpix+flowers. The visual content of "Millefolium" was thereby generated by artificial intelligence, before being passed onto the painter to iterate on a final time. This process plays with the idea of the machine as content creator, giving it the responsibility to decide what imagery the final painting should depict, rather than the artist herself. Simultaneously, it creates a conversation between artist and machine, beginning with the artist's input, the machine responding by mutating it, and ending with the artist's final output.</p>
          <p>See more about "Millefolium" here.</p>
        </div>

      </Project>
  </Layout>
)

export default AiArtPage;
